moevm/moodle_js_actions_collector

- server/models/session_data.py
- server/models/user.py
Описаны классы, соответствующие объектам, с которыми будет взаимодействовать серверная часть приложения
> #11 Сформировать модели

- client/.dockerignore
- client/Dockerfile
- docker-compose.yaml
Запуск осуществляется из файла docker-compose.yaml с помощью следующей команды:
`docker-compose up frontend`
> #63 Сформировать докер для клиентской части

- client/Dockerfile
- client/nginx.conf
- docker-compose.yaml
В качестве веб-сервера настроен nginx. 
Для дальнейшего написания запросов к backend-серверу необходима настройка cors.
> #66 Ошибка при запуске докер контейнера с клиентом

- client/nginx.conf
- client/package-lock.json
- client/package.json
- client/src/colors.css
- client/src/components/Navbar.vue
- client/src/components/Pages/CreateUserPage.vue
- client/src/router.js
- Реализована страница создания пользователя
- Внесены небольшие изменения в nginx.conf, для корректной отправки запросов на сервер
- На данной итерации так как нет задачи настроить валидацию на стороне frontend, для успешного создания пользователя необходимо вводить корректный почтовый домен, к примеру, test.user@mail.ru
> #52 Реализовать страницу создания пользователя

- client/src/components/Pages/StatisticsPage.vue
- client/src/components/Statistics/StatisticsTable.vue
Страница статистики отправляет запрос на сервер и представляет полученные данные
> #26 Реализовать взаимодействие с клиентом

- stat_tracker/moodle_stat_tracker_all.html
- stat_tracker/moodle_stat_tracker_specified_elements.html
Добавлена функция, которая позволяет вытаскивать из кода страницы информацию о пользователе (Фамилию, Имя). Поскольку, тестирование невозможно на сайте, на котором она будет использоваться, я ее пока что никуда не подключал, но она работает в консоли сайта.
> #43 Поиск информации о пользователе

- stat_tracker/moodle_stat_tracker_all.html
- stat_tracker/moodle_stat_tracker_focus_on_tab.html
- stat_tracker/moodle_stat_tracker_specified_elements.html
Добавлено отслеживания перехода на другие вкладки браузера
> #41 Реализация недостающих обработчиков

- stat_tracker/moodle_stat_tracker_all.html
- stat_tracker/moodle_stat_tracker_focus_on_tab.html
- stat_tracker/moodle_stat_tracker_specified_elements.html
Теперь отображается трекинг всех элементов, заявленных для трекинга.
> #87 В базу данных сохраняется только нажатие на кнопку

- stat_tracker/moodle_stat_tracker_focus_on_tab.html
В скрипте, который позволяет трекать активность вкладок изменен тип элемента
> #89 Измение типа элемента page

- client/src/colors.css
- client/src/components/Filters/Filters.vue
- client/src/components/Filters/Search.vue
- client/src/components/Navbar.vue
- client/src/components/Pages/StatisticsPage.vue
- client/src/components/Statistics/StatisticsTable.vue
Реализован поиск по данным в таблице. При введении данных для поиска в соответствующее поле сам поиск по таблице осуществляется по всем столбцам и строкам без учета регистра и находит все вхождения подстроки.
> #32 Реализация поиска

- stat_tracker/moodle_stat_tracker_specified_elements.html
ТЕперь внутри функции сохранения элемента при условии что мы сохраняем кнопку в ее имя будет вставляться внутренний текст нажатой кнопки.
> #96 Записывание реальных названий кнопок

- init-mongo.js
- server/Dockerfile
- server/requirements.txt
- server/src/api/endpoints/statistics.py
- server/src/core/modules/database/statistics.py
- server/src/core/modules/service/statistics.py
- server/src/models/filter.py
- server/src/models/session_data.py
added filtering data by time, changed date/time to timestamp in db and models, fixed dockerfile for server
> #17 Добавление фильтрации данных сессий по времени

- init-mongo.js
- openapi.yaml
- server/src/models/session_data.py
Удалена группы у студента, добавлен student_id, отредактирован формат дат в init-mongo
close #112
> #112 Убрать номер группы из модели данных

- server/src/api/api.py
- server/src/api/endpoints/authorization.py
- server/src/core/modules/database/user.py
- server/src/core/modules/service/authorization.py
- server/src/depends.py
- server/src/models/user.py
Реализован вход пользователя на стороне сервера.
> #21 Реализовать процесс авторизации пользователя

- stat_tracker/moodle_stat_tracker.html
добавлены функции извлечения почты и id пользователя на moodle
> #95 Изучить возможность получения данных пользователя из профиля

- client/src/components/AuthForm.vue
- client/src/components/Navbar.vue
- client/src/components/Pages/AuthorizationPage.vue
- client/src/components/Pages/CreateUserPage.vue
- client/src/components/Pages/StatisticsPage.vue
- client/src/router.js
На стороне клиента реализована авторизация: вход(взаимодействие с сервером) и выход. Добавлена работа с session storage для возможности использования сайта только в случае успешного входа в систему.
> #129 Реализовать процесс входа и выхода из системы на клиенте

- stat_tracker/moodle_stat_tracker.html
> #132 Функция вытягивания email пользователя написана некорректно

- stat_tracker/moodle_stat_tracker.html
добавлено отслеживание событий копирования и вставки
> #100 Изучить возможность отслеживания копирования из буфера обмена

- client/src/components/Pages/AllUsersPage.vue
- client/src/components/Tables/UsersTable.vue
На стороне клиента реализована возможность удалять пользователей из системы. Удалить администратора из системы нельзя.
> #142 Реализовать удаление пользователей

- .github/workflows/build-check.yml
- .github/workflows/lable_merge_conflicts.yml
- docker-compose.yaml
Добавлены GA для сборки и проверки работоспособности контейнеров, а также для проверки ПР на конфликты
> #131 Интеграция Github Actions 

- .github/workflows/build-check.yml
По умолчанию job искала .yml, а у нас .yaml
> #146 Исправление GA для сборки и проверки контейнеров

- stat_tracker/moodle_stat_tracker.html
формат времени изменен на ISO-строку (которая включает в себя миллисекунды)
> #117 Изменить формат оправки времени из мудл

- server/src/api/endpoints/statistics.py
- server/src/models/session_data.py
Оказалось, проблема в том, что отправлялось с мудл, но зато пофиксил импорты
Если с мудл останется проблема - для отправки даты использовать
```js
"timestamp": new Date().toISOString() 
```
> #135 Фикс даты

- openapi.yaml
> #153 Обновление спецификации

- client/public/index.html
- client/src/components/Pages/CreateUserPage.vue
- Изменено отображаемое название сайта на e.moevm statistics
- Добавлен Navbar на странице создания пользователя
> #145 Корректировки отображения на стороне клиента: название сайта и страница создания пользователя

- client/public/data.json
- init-mongo.js
- server/src/models/session_data.py
- stat_tracker/moodle_stat_tracker.html
> #165 Удалить поле session

- server/Dockerfile
- server/src/api/endpoints/statistics.py
- server/src/core/modules/database/statistics.py
fixes #163, fixes #164 
Исправлена таймзона на сервере - теперь там Europe/Moscow (Было UTC+0), добавлен генератор текущей даты для дефолтного параметра запроса
> #163 Исправление ошибок, связанных с отображением времени

- client/public/data.json
- client/src/components/Chart.vue
Добавлено:
- Масштабирование графика по колесику мыши
- Перетаскивание холста с графиком
- css стиль для компоненты
> #150 Реализовать масштабирование графиков

- openapi.yaml
- server/extract-openapi.py
- server/src/models/session_data.py
- stat_tracker/moodle_stat_tracker.html
Fixes #162 
Добавлены типы событий, обновлена спецификация api, добавлен скрипт для генерации openapi.yaml на основе swagger'a
> #162 Добавление типов событий

- stat_tracker/moodle_stat_tracker.html
> # 179 Добавление миллисекунд во временную метку

- client/package-lock.json
- client/package.json
- client/src/components/Pages/AuthorizationPage.vue
- client/src/components/Pages/CreateUserPage.vue
- client/src/components/Pages/StatisticsPage.vue
- client/src/test/test-selenium.js
Реализованы базовые тесты для проверки клиентской части с помощью `Selenium.`
Тестируется следующее:
- Вход в приложение
- Обработка основных действий на странице статистики
- Отображение всех пользователей на странице all-users
- Добавление пользователя
Инструкция по запуску тестирования
На данный момент тестирование локальное. Необходимо с помощью `npm run install` подтянуть новые библиотеки. Поднять приложение с помощью `docker-compose.prod.yaml` Перед этим, очистить `volumes`, удалить старые образы. Далее в терминале своей системы перейти в папку проекта `client/src/test`. Запуск с помощью команды `node test-selenium.js`. Если ругается, что не установлен `nodejs` - установите. По окончанию тестирования в папке появится файл `test.txt` - логирование тестирования.
> #139 Реализовать интеграционные и функциональные тесты для клиента

- client/src/components/Pages/StatisticsPage.vue
- client/src/components/Tables/StatisticsTable.vue
Столбик "Действие" разбит на "Тип действия" "Тип события" и "Название элемента"
> #197 Добавить поля в таблице

- init-mongo.js
- server/src/models/session_data.py
При добавлении не нашла типов данных для html, поэтому перед внутренними кавычками поставила "\". Других вариантов сохранения в виде строки не придумала, но если будут какие-то другие способы - могу доделать.
> #208 Добавить поле html элемента в модель

- server/src/api/endpoints/statistics.py
- server/src/core/modules/database/statistics.py
- server/src/core/modules/database/user.py
- server/src/models/filter.py
Closes #191
Добавил фильтрацию по всем отображаемым полям.
На скрине не все реализованные фильтры - подробнее в swagger (для тестирования переключиться на эту ветку):
При беглой проверке - отправка из мудла не упала, на фронте фильтрация по дате все еще работает.
> #191 Добавление фильтрации

- client/public/data.json
- client/src/components/Chart.vue
Исправлена таймзона, теперь tooltip совпадает с значениями на шкале
> #210 Неверное отображение даты на графике

- .github/workflows/build-check.yml
> #199 Зафиксировать версию Ubuntu в github-runner

- server/src/api/api.py
- server/src/api/endpoints/statistics.py
Closes #19 
Добавил возможность скачивать файл с выбранными по фильтрам записями. Для проверки переключиться на данную ветку, поднять монгу и бэкенд и перейти в сваггер. Экспортируются данные в JSON-формате.
> #19 Скачивание отчета

- openapi.yaml
- server/src/api/endpoints/statistics.py
- server/src/core/modules/database/statistics.py
- server/src/core/modules/service/statistics.py
- server/src/depends.py
- server/src/models/session_data.py
Closes #193 
Добавил модель для хранения данных о странице. ID записи возвращается при создании, этот ID требуется для связи записей статистики с данными из новой коллекции. Также добавил методы для создания/получения всех записей из коллекции. Добавлена возможность скачать файл с данными из новой коллекции
> #193 Добавить коллекцию с данными о странице

- client/src/components/Pages/StatisticsPage.vue
> #238 Исправление неверной фильтрации

- client/src/components/Chart.vue
- client/src/components/Pages/StatisticsPage.vue
- client/src/components/Tables/UsersTable.vue
Внесены следующие изменения на клиенте:
- Удалены иконки удаления у администраторов в таблице, где отображаются все пользователи
- Изменено расстояние у кнопок "Поиск" и "Сброс" на страницы отображения статистики
- Изменено имя у кнопки, возвращающей начальный масштаб графика
> #232 Редактирование отображения. Фильтрация и таблица пользователей.

- docker-compose.yaml
- server/.env
> #240 Вынести данные авторизации и переменные среды в .env 

- client/src/components/Pages/StatisticsPage.vue
- client/src/components/Tables/StatisticsTable.vue
Удален столбик с ссылкой на страницу из таблицы статистики
> #243 delete field url

- stat_tracker/moodle_stat_tracker.html
теперь событие scroll при срабатывании в первый раз записывается, после чего на его запись выставляется таймаут на 5 срабатываний.
в случае моего ноутбука удалось уменьшить количество записей с ~12 до 2.
эффект будет зависеть от размеров окна браузера
длину таймаута можно изменить в ифе на 248 строчке путем замены 5 на более интересующий вариант
```javascript
if (mousewheelCounter == 5){
mousewheelCounter = 0
``` 
resolves #228
> #228 Изучить сбор событий scroll

- stat_tracker/moodle_stat_tracker.html
- stat_tracker/moodle_stat_tracker_without_script.html
Данные отправляются при нажатии кнопок проверить и кнопок перехода на следующее задание. Проблема - кнопки перехода на следующую страницу имеют тип input, а не button, из-за чего запись в бд выглядит так: 
Фикс буду делать вместе с фиксом [object HTMLInputElement] в другом ПР
> Add beforeunload event listener
